version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db-wishlist
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
